import type { Metadata } from "next";
import "./globals.css";


import Header from "@/components/Header";
import { ThemeProvider } from "next-themes";

import {
  ColorSchemeScript,
  MantineProvider,
  mantineHtmlProps,
} from "@mantine/core";

export const metadata: Metadata = {
  title: "Poster | Landing",
  description: "Generated by create next app",
  icons: {
    icon: "/imgs/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&family=Raleway:wght@400;700&family=Merriweather:wght@400;700&family=Dancing+Script:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="dark:bg-dark-700">
        <ThemeProvider    attribute="class">
          <Header />
          <MantineProvider>{children}</MantineProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
